

services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - optica-network
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - optica-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - optica-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - optica-network
    environment:
      MYSQL_ROOT_PASSWORD: mnbv
      MYSQL_DATABASE: db_usuarios
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  mongodb-historial:
    image: mongo:7
    container_name: mongodb-historial
    ports:
      - "27018:27017"
    networks:
      - optica-network
    volumes:
      - mongo_data:/data/db

  mongodb-pacientes:
    image: mongo:7
    container_name: mongodb-pacientes
    ports:
      - "27019:27017"
    networks:
      - optica-network
    volumes:
      - mongo_pacientes_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  redis-citas:
    image: redis/redis-stack:latest
    container_name: redis-citas
    ports:
      - "6379:6379"
      - "8003:8001"
    networks:
      - optica-network
    restart: always

  ms-usuarios:
    build: ../servicios/servicio-usuarios
    container_name: ms-usuarios
    depends_on:
      - kafka
      - mysql
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - optica-network
    restart: on-failure 
    environment:
      PORT: 8082
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mnbv
      DB_NAME: db_usuarios
      KAFKA_BROKER: kafka:9092
      JWT_SECRET: una_clave_secreta_larga_y_dificil
      EUREKA_HOST: eureka-server

  ms-autenticacion:
    build: ../servicios/servicio-auth
    container_name: ms-autenticacion
    depends_on:
      - kafka
      - mysql
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - optica-network
    restart: on-failure 
    environment:
      PORT: 8081
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mnbv
      DB_NAME: db_usuarios
      KAFKA_BROKER: kafka:9092
      JWT_SECRET: una_clave_secreta_larga_y_dificil
      JWT_EXPIRES_IN: 8h
      EUREKA_HOST: eureka-server

  ms-historial:
    build: ../servicios/servicio-historial
    container_name: ms-historial
    depends_on:
      - kafka
      - mongodb-historial
      - eureka-server
    ports:
      - "8085:8085"
    networks:
      - optica-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  servicio-pacientes:
    build: ../servicios/servicio-pacientes
    container_name: servicio-pacientes
    depends_on:
      - mongodb-pacientes
      - kafka
      - eureka-server
    ports:
      - "8084:8001"
    networks:
      - optica-network
    environment:
      MONGO_URL: mongodb://admin:admin123@mongodb-pacientes:27017/?authSource=admin
      KAFKA_URL: kafka:9092
      PORT: 8001
    restart: on-failure

  servicio-citas:
    build: ../servicios/servicio-citas
    container_name: servicio-citas
    depends_on:
      - redis-citas
      - kafka
      - eureka-server
    ports:
      - "8083:8002"
    networks:
      - optica-network
    environment:
      REDIS_URL: redis://redis-citas:6379
      KAFKA_URL: kafka:9092
      PORT: 8002
    restart: on-failure

  #frontend:
    #build: ../frontend
    #container_name: frontend
    #ports:
      #- "5173:5173"
    #networks:
      #- optica-network
    #depends_on:
      #- servicio-pacientes
      #- servicio-citas
    #restart: on-failure

volumes:
  mysql_data:
  mongo_data:
  mongo_pacientes_data:

networks:
  optica-network:
    driver: bridge