server.port=8085

spring.application.name=ms-historial

# Mongo
spring.mongodb.uri=mongodb://mongodb-historial:27017/historialdb
# Kafka
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=historial-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

#jwt
spring.main.allow-bean-definition-overriding=true
jwt.secret=una_clave_secreta_larga_y_dificil