spring.application.name=servicio-historial

server.port=8085

# MongoDB (Spring Boot 3+ configuración moderna)
spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=historialdb
spring.mongodb.username=admin
spring.mongodb.password=admin123
spring.mongodb.authentication-database=admin

# Opcional pero útil para desarrollo (ver queries en consola)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG